INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (1,'Van Dijk Consult','Rick.Jessen@gawab.co.uk','1-936-5015');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (2,'Warner Lambert','K.Pyland5@dolfijn.co.uk','685-415-0416');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (3,'CMG Information Services','HHaynes5@yahoo.cn','1-641-143-8909');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (4,'BlackSoft','Mick.Brennan4@web.dk','1-767-7518');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (5,'FinlandAir','Ronald.Mairy1@mobileme.be','597-5333');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (6,'Dacia','Fons.Arnold5@freeweb.co.uk','1-728-4538');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (7,'Oracle Corp.','Hans.Chwatal@mobileme.com','489-9747');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (8,'Excalibur Technologies','J.Gibson2@kpn.cn','402-282-7575');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (9,'Heineken','PetraTurk@weboffice.org','950-0313');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (10,'Briomos','GArcadi3@mail.no','170-3030');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (11,'Zjing International','FredLaudanski@live.org','404-7289');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (12,'Ahold','REmerson@telefonica.cn','1-596-2415');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (13,'Eelonso Systems','WilliamKellock@dolfijn.nl','1-764-883-7249');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (14,'Van Wiegen Verzekering','MDaley2@aol.gov','266-0725');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (15,'Oracle Corp.','Ronald.Mairy@mobileme.nl','450-317-8303');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (16,'Ibranas','E.Perilloux@mobileme.no','1-867-8872');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (17,'Goldman Sachs','Freddy.Queen3@yahoo.dk','578-9944');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (18,'Premenos Technology','RThaler1@freeweb.cc','1-854-775-2628');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (19,'Van Sterkendam Consult','VincentGuethlein@myspace.com','299-6841');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (20,'UStep','GGieske1@dolfijn.cn','1-907-2983');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (21,'RTI Bank','RichardHardoon@myspace.it','1-908-864-4516');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (22,'DisplayTools co','RGriffioen2@gmail.es','244-3185');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (23,'Blata','RonGerschkow@telfort.no','006-5803');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (24,'FTP Software','Peter.Haynes@yahoo.es','1-643-4485');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (25,'FTP Software','Geoffry.Nefos@yahoo.fr','1-633-023-9560');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (26,'Ybena Computers','Bas.Ionescu@mobileme.net','471-6340');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (27,'Spyker','Nick.Jones@libero.net','1-330-0395');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (28,'Djingy Phones','FrankGriffith1@telfort.be','1-417-007-1638');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (29,'Tacan','Frank.Brumley@web.net','971-5211');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (30,'AtlantaAir','T.Thompson1@mobileme.org','1-211-3321');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (31,'Chekfree','H.Ayers5@mymail.nl','010-6495');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (32,'HVX Works','BillBogdanovich@mymail.be','1-669-0639');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (33,'Abbot','Milan.Novratni@live.com','1-519-145-8723');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (34,'Van Wiegen Beveiliging','CGriffioen1@weboffice.be','238-8644');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (35,'Spyglass','D.Crocetti4@mymail.gov','1-028-304-3075');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (36,'Ulani Communications','RDittrich1@libero.gov','1-777-768-1518');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (37,'Zeneca','PDulisse@yahoo.dk','1-394-622-7166');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (38,'Lederle','PierreHerring@lycos.gov','1-710-101-5777');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (39,'Scheider','A.Huffsmitt@mobileme.com','1-596-978-2556');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (40,'Zjongo International','C.Van Toorenbeek@gmail.ca','1-522-1354');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (41,'KWIP Shoes','Geoffry.Climent@web.no','1-794-290-5427');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (42,'GUIWorks gmbh','Rick.Laudanski5@dolfijn.co.uk','1-941-476-0309');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (43,'KR Transport','P.Bergdahl2@gawab.co.uk','069-0314');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (44,'Crocan','SEcchevarri3@gmail.us','580-3768');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (45,'Njingy Stores','MattGriffioen3@gawab.dk','1-733-444-6799');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (46,'Quarterdeck','FrankyOlson@telefonica.com','1-060-706-5934');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (47,'HBX Consult','Ronald.Vanderoever@myspace.be','1-934-814-5687');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (48,'BroadVision','Dan.Mariojnisk@telfort.de','147-850-0273');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (49,'Kovotna Consultants','GThompson3@excite.cc','450-107-0245');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (50,'Kreitlar Management','Richard.Brumley@excite.no','1-743-1780');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (51,'Imtech','VictoriaSymbouras@mymail.org','1-847-7697');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (52,'WAMM Software','RickFox1@kpn.de','1-757-5248');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (53,'Alanco Consultancy','GPerilloux@mymail.ca','100-968-4942');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (54,'Rabobank','BenMariojnisk@lycos.it','1-806-141-0228');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (55,'MerckSharp&Dohme','BDitmanen1@aol.co.uk','695-912-7982');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (56,'Brinkman BV','MVisentini@mymail.cc','1-832-2066');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (57,'Open Market','Richard.Pierce@msn.de','499-172-5466');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (58,'FTP Software','Johan.Shapiro4@web.nl','486-165-6343');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (59,'Leo','MickByrnes@lycos.be','1-587-3716');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (60,'BVDS Communications','RickHoyt@dolfijn.cc','1-248-4797');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (61,'Mexx IT','C.Pekaban3@weboffice.nl','492-2063');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (62,'Ulan Computers','GHelfrich@hotmail.no','729-798-8483');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (63,'Sharpe and Pitt IT Solutions','WillSlocum1@libero.nl','502-8413');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (64,'Ferry and Burns Data Solutions','MandyGoodnight5@web.net','867-6667');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (65,'Silicon Graphics','DickNaff@myspace.no','871-555-9260');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (66,'Sandoz','RArnold@live.gov','1-325-1984');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (67,'Pepsi','WillQueen2@libero.net','814-2962');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (68,'Njong Services','PeteDitmanen@hotmail.us','1-280-9032');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (69,'Wehkamp BV','MattEsperiza@live.fr','1-803-8894');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (70,'Netcom On-Line Communications Services','Rick.Poissant@msn.be','105-8122');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (71,'GoldSystems','M.Schubert5@mymail.com','1-837-3973');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (72,'Getronics','E.Orcutt@telfort.no','995-132-2324');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (73,'Poolta','Bas.Gieske4@hotmail.nl','1-350-480-1012');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (74,'System U','Frans.Knight@gawab.cc','1-007-638-6134');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (75,'Pitt Works','G.Angarano@gawab.ca','1-650-0276');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (76,'EMI Music','Leon.Gua Lima@aol.us','1-598-199-8356');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (77,'Meinders Meubelen','Matt.Meterson5@web.dk','791-274-7528');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (78,'Djong','HMcCrary1@weboffice.fr','1-519-458-1890');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (79,'Vardisio','PeterWeaver@dolfijn.com','1-233-6685');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (80,'BlackPoint','K.Olson4@freeweb.us','1-110-666-4187');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (81,'GreenSystems','LBrowne@aol.fr','295-274-2229');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (82,'NorthGo Deuren','WilliamOyler5@myspace.com','1-128-2751');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (83,'NovoNordisk','LBlount@telefonica.fr','1-716-718-3838');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (84,'MyWorks corp','MartMulders5@web.net','440-4306');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (85,'Zaragoza Bank','Mattijs.Goodman@gawab.gov','646-8646');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (86,'Sheridan Systems','Mike.Maribarski@kpn.no','1-242-930-1910');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (87,'Astra','TreesLong3@lycos.com','1-618-981-1866');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (88,'ParkeDavis','BasWolpert4@myspace.ca','1-248-8673');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (89,'DotNet','RichardAntonucci@mail.it','193-812-8784');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (90,'SpainAero','DavidBright@yahoo.org','1-060-4991');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (91,'Mecklermedia Corp.','LeonVan Toorenbeek4@msn.ca','235-937-1939');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (92,'TRDS Consultancy','SvenBeckbau4@telfort.us','421-109-1640');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (93,'Van Waal Bouw','Hans.Warner1@myspace.be','1-749-2359');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (94,'Leo','Will.Jessen@hotmail.us','1-685-727-1415');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (95,'Zaal Buxus','EricTrainor1@libero.nl','1-229-3083');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (96,'Vardisio','MadeleinReyes3@mymail.net','1-358-9688');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (97,'PhoenixAir','FemkeBrendjens@mobileme.com','1-691-8482');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (98,'Dista','Bas.Freed1@kpn.com','1-634-7331');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (99,'BASF','MartinPengilly2@mymail.net','1-488-2744');
INSERT INTO "public"."cliente" ("idcliente","nombre","email","telefono") VALUES (100,'MR Bank','L.Storrs@mymail.gov','013-080-0752');