INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (1,'RN Technics','1-587-4351','I.Freeman@telfort.it','16 Glenridge Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (2,'Zjongo Services','876-640-3189','LBaltec5@telefonica.cc','648 South MacArthur');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (3,'MiraVori','749-509-9599','GeoffryGuyer3@live.gov','32 Serang Place');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (4,'UV Bank','1-127-093-6236','Kylie.Friedman@weboffice.de','854 Hidden Valley Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (5,'BeterBed','1-367-082-1043','NickOverton@web.ca','9320 Everglades Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (6,'TDK','1-940-6413','VictoriaPhillips@gmail.de','872 Warren Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (7,'Macromedia','603-551-5625','Bas.Francis@telfort.be','166 Nortman Blvd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (8,'Dista','1-313-654-5694','Rogier.Ionescu4@hotmail.cn','398 Lindstrom Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (9,'MasterSoftware','041-406-2951','Will.Griffith4@dolfijn.net','07 Serena Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (10,'Edify','1-616-048-1040','RIonescu@aol.us','08 Fairfield Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (11,'YXS Shoes','1-294-904-0981','Mick.Thaler@freeweb.gov','193 New Michigan Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (12,'Cage and Cromwell Data Solutions','668-015-3211','PeterWhite3@msn.net','1689 Stokes Rd.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (13,'Cage and Marks Data','1-479-0026','ECramer5@telefonica.it','219 Village Road East');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (14,'Trendhopper','1-980-1064','Peter.Cramer@weboffice.gov','57 Robin Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (15,'Brino','1-092-1230','Paul.Rauch5@live.us','96 W. Sunnyside Ave.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (16,'SAAB','1-192-549-7184','SjorsWaldo5@freeweb.it','9049 Swan Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (17,'VV Training','1-350-3119','Y.Blount5@telfort.cn','65 Brandon Marshall Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (18,'KZC Works','1-920-9970','JakeLezniak@yahoo.be','5 Charlotte Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (19,'GoodWorks co','1-769-3247','FreddyFreed@telefonica.dk','8533 Chesterfield Road South');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (20,'EuroWorx co','1-296-5676','Nick.Sterrett@telefonica.gov','4350 Shallowford Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (21,'BristolMyers','879-545-9641','Peter.Herzog5@freeweb.it','2251 Prospect Hill');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (22,'UPC','1-810-2094','IPoplock@telefonica.fr','247 Village Road East');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (23,'NUWorx corp','728-775-6871','LNovratni5@freeweb.be','3 University ave.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (24,'GreenConsult','850-0767','G.Phelps@weboffice.fr','353 Regency Plaza');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (25,'Etopo Consultancy','1-680-543-9540','BillKnight2@mymail.org','8443 Terminal Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (26,'Van Sterkendam Constructies','195-1284','MaartenByrnes1@aol.es','24 Hidden Valley Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (27,'DenmarkAir','1-995-7337','DavidPetterson3@myspace.nl','113 Brooke Valley Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (28,'Ibranas','1-936-654-4998','R.Mayberry@hotmail.nl','65 River Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (29,'Simopix','138-2402','Victoria.Sharp@myspace.ca','05 S. Brockbank Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (30,'Abonso Tech','1-955-364-6585','Frans.Moore@myspace.es','679 Terminal Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (31,'Casco','1-174-315-1348','Brent.Kingslan@mobileme.org','4 Wellington Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (32,'BetterOffice','644-3712','BiancaKoch@mymail.fr','4 2th Ave.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (33,'Lycos','549-3611','PaulAnderson@mobileme.gov','967 Amadonna Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (34,'Organon','200-5671','Bill.Moore@mobileme.it','6 S. Brockbank Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (35,'JanssenCilag','1-756-8587','BillBrady@mobileme.nl','4839 Danielle Ct.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (36,'Cszerwinski Informatics','1-303-824-8026','L.Wooten@live.us','47 Stokes Rd.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (37,'RKKW Builders','1-739-675-7948','Suus.Barnett@telefonica.cc','937 Greenheath Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (38,'Notalya Consultancy','484-1520','Jake.Blacher@kpn.es','2717 Business Center Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (39,'C&A','1-286-515-0614','JMorton3@yahoo.fr','6391 Village Road East');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (40,'Achat','120-569-8598','WilliamKellock@gmail.cn','7 Fairfield Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (41,'Mongy Aero','040-6850','Hans.Stockton@telefonica.net','483 Hidden Valley Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (42,'PTT Telecom','275-675-8532','William.Chapman@excite.es','5072 Weber Street North');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (43,'Van Dijk Boeken','597-1552','YFreeman@msn.es','29 N Broadway');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (44,'Compuserve','452-002-1528','FransGildersleeve@telefonica.net','1308 Redwood Ave.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (45,'EMI Music','1-091-434-3914','RicoGrote@freeweb.us','4 Spottswood Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (46,'Van Toorn Woonwinkel','1-184-776-5956','BrentOtto5@telfort.dk','3980 Stony Field Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (47,'Washinghton Bank','1-589-5865','WillOyler@yahoo.be','5620 Canyon Crest Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (48,'Van Voort Constructies','1-117-071-3691','EZia@telefonica.net','27 Summer Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (49,'LXP Works','1-411-8003','BobKrutkov3@web.de','52 Walkers Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (50,'Zurich Bank','1-783-0099','Ann.Goodnight5@live.cc','5924 Sungrave Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (51,'Brierman Consultancy','078-176-5795','CamillaHuffsmitt@mail.cc','9215 Sutter St');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (52,'MossTech','023-399-2148','KimMaribarski4@dolfijn.cn','29 Palos Verdes Mall');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (53,'Cszerwinski Informatics','472-7067','Y.Ratliff3@freeweb.nl','5278 Warwick Square');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (54,'The Datanamic Group BV','564-898-3689','CarlaDeWilde@msn.ca','4836 Wilder St.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (55,'Free Record Shop','295-8644','Fred.Watson1@libero.cn','700 ZW Bruce Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (56,'Bank Labouchere','901-2488','EmmaThompson@web.it','114 Regency Plaza');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (57,'FTP Software','833-476-6983','RickMcCormick2@weboffice.no','97 N. Glenoaks Blvd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (58,'IDEX','066-1350','ISlocum@hotmail.it','08 Meadow Walk');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (59,'FTP Software','795-6369','KOtto5@dolfijn.es','5 Crookston Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (60,'Casco','1-991-4598','HankWood@myspace.be','4601 Morningside Dr');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (61,'Johnson & Johnson','131-8245','EHankins@web.de','84 Regency Plaza');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (62,'FinaData','1-655-5510','SvenPatricelli@aol.no','88 Barrenger Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (63,'NUDS Systems','1-254-170-4993','Brent.Wakefield@web.co.uk','371 Grassmere Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (64,'Beecham','1-949-8967','Agnes.Gua Lima@web.no','409 Weber Street North');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (65,'Van Teken Montage','276-847-4544','V.Poole@live.es','73 Colette street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (66,'Trinity','251-3356','Y.Daughtery3@mobileme.cc','3 Dairy Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (67,'Glaxo','1-609-6891','LiamBotsik@mobileme.nl','3874 Everglades Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (68,'Van Steen Adviseurs','1-630-720-4780','HankDepew2@hotmail.co.uk','3131 Weber Street North');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (69,'Grupo Santander','958-743-5864','FrankSterrett2@dolfijn.net','14 Devonshire Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (70,'Lisboa Bank','1-529-4129','BiancaKing2@mobileme.co.uk','04 Willingdon Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (71,'Cascade Communications','695-445-0384','JackSwaine4@libero.us','2169 Willingdon Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (72,'FTP Software','1-861-779-1874','Ciskavan het Hof2@weboffice.gov','5 South 75th Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (73,'Alan Communications','1-261-5993','PetraDeBerg@msn.de','363 Wicksicam Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (74,'Fenomen','741-6338','JimBrennan@yahoo.co.uk','413 Copeland Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (75,'Sanofi','1-138-6735','S.Makelaar@gawab.it','9278 Warm Spring Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (76,'Weclo Media','639-1155','Geoffry.Kuehn5@gawab.no','5141 Jefferson Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (77,'Raptor Systems','1-052-349-2045','B.Uitergeest@web.org','6 Woodside Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (78,'RedSoft','1-032-7670','MaartenBlacher3@web.us','77 King Salmon Place');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (79,'OrangeData','1-032-369-3382','RichardBoyer5@telfort.be','695 Ninth Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (80,'Cap Gemini','1-657-431-1760','DickTrainor1@hotmail.co.uk','43 Gascony Pl.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (81,'Van Tonen Constructies','622-810-6703','Johan.Queen4@weboffice.org','2328 N. Pine Grove');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (82,'Brasserie De Meiden','089-0155','AgnesNovratni1@aol.com','980 Northcreek Parkway');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (83,'RQS Group','724-402-3995','PeterSpensley@freeweb.gov','63 Arlington Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (84,'Infoseek','1-921-412-0819','PAllison5@telefonica.be','1 Brimming Boulevard');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (85,'FinlandAir','1-120-146-3491','Y.Petrzelka@msn.cn','9 Summer Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (86,'MiraVori','486-1020','Isolde.Moore3@msn.es','5540 Centerville Place');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (87,'GoldShopToGo','917-495-7649','FransWatson3@mail.ca','46 Business Center Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (88,'Ning Stores','354-233-7026','HankWilliamson@dolfijn.ca','66 Stony Field Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (89,'Michelin','1-157-3569','HWaldo@gmail.co.uk','9347 Arlington Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (90,'ParkeDavis','683-3089','Frans.Kingslan@excite.us','2403 ZW Bruce Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (91,'Weber Koeltechniek','811-250-6921','LindsyMatthew@excite.cc','2695 S. Brackbank Dr');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (92,'Catino','380-776-6560','RStockton5@gawab.co.uk','773 Business Center Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (93,'Fortis','1-619-675-0812','FreddyJessen5@telfort.ca','76 Springfield Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (94,'Symantec','1-466-6462','T.Cantere@telfort.com','48 Madden Blvd.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (95,'DallasAero','853-8048','VictoriaLangham1@gawab.fr','48 Charlotte Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (96,'Wang Computers','224-345-1939','GZurich@gmail.cn','2252 B. Jackson Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (97,'OrangeShop2Go','1-544-3269','MilanCarlos1@live.net','8229 Hidden Valley Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (98,'Pitt and Russell Data Solutions','1-833-5871','Y.Yinger@telfort.us','4 W. Broadway');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (99,'Excalibur Technologies','882-1786','HankStockton@yahoo.es','51 Eisenhower Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (100,'Scholtes Vleeswaren','643-076-2022','E.Wong1@msn.be','7 One Park Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (101,'BrownShop2Go','1-543-511-3192','HWilliams3@freeweb.org','368 Faught Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (102,'Super Confex','571-6910','RicoFriedman@telefonica.be','10 W. Broadway');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (103,'Pepsi','171-656-6260','Frans.Chapman@yahoo.co.uk','28 South Main');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (104,'Sun Microsystems','1-300-8399','R.Kuehn5@lycos.it','8176 Colette street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (105,'Super Confex','823-0931','Patrick.Cohen@freeweb.co.uk','38 Mount Helena Av.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (106,'Intuit','822-094-2561','RickMorton@excite.fr','1 Barrenger Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (107,'Spectradat','1-839-534-0435','Victor.Browne@yahoo.be','2406 Charlotte Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (108,'Van Doorn Uitzendbureau','1-565-9164','WillCramer2@mymail.nl','865 Floribunda Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (109,'Van Houweningen Ass.','1-841-319-4962','RichardLamere@gawab.org','79 E. Marions Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (110,'IBM','775-3078','Camilla.Krutkov@dolfijn.fr','0701 Weber Street North');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (111,'Van Waal Montage','096-535-1313','Bill.Deleo@gmail.org','05 Medford St');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (112,'Pandata','775-4667','Bas.Hendrix@kpn.gov','5282 Unbridle Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (113,'Organon','077-519-1497','V.Simonent3@gawab.nl','1715 Northpark Blvd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (114,'MiraVori','024-900-5804','PMcnally@excite.gov','169 Cheltenham Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (115,'Zaragoza Bank','837-864-2182','RBrowne@hotmail.cn','3309 Warren Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (116,'Raptor Systems','1-346-8783','Richard.Mitchell@kpn.fr','7896 Highland Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (117,'Laterna Corp.','084-3534','Bas.Massingill@libero.cc','2591 Fairfield Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (118,'SunRiver','1-537-291-7163','NadineOlson@hotmail.no','223 North 0th Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (119,'BASE','1-370-929-4283','EDulisse@freeweb.us','298 Meadow Walk');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (120,'TDK','026-179-1083','HankMitchell4@myspace.fr','666 Shallowford Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (121,'Etapa Consultancy','1-084-170-5105','TonFrega5@lycos.fr','2613 Southwest Blvd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (122,'ChinaAir','1-705-811-0046','Nick.Watson@hotmail.ca','09 Greenheath Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (123,'Brioflex','805-804-4136','Frank.Spensley@lycos.org','3 Sungrave Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (124,'Seven Days Center','723-1126','L.Alspaugh@telfort.us','2 Copeland Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (125,'Cage Works','275-917-0790','MPolti@live.org','1683 2th Ave.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (126,'Fulcrum Technologies','1-818-4165','M.Browne5@myspace.be','15 South 42th Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (127,'Ethical Generics','1-508-5188','V.Zapetis4@aol.es','746 Charlotte Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (128,'Orion','1-584-4298','Victor.Cross@mail.net','43 Gilbert Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (129,'Brinkman BV','869-770-9879','GeoffryCohen4@web.cn','7 Windbrook Crs');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (130,'Merck and Marks Data','1-639-9021','Frank.Willis3@telfort.dk','63 Ninth Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (131,'Cisco Systems','228-3346','Pierre.Chwatal@telefonica.cc','8 River Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (132,'Camelot','680-2509','Sydney.Robertson@gmail.us','99 Eisenhower Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (133,'Elan Computers','467-699-4929','V.Trainor5@aol.it','5977 Maxwell Ave.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (134,'EMI Music','232-4537','H.Boyer2@hotmail.com','25 Tremont Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (135,'MiraVori','1-497-895-5450','MaddyBlacher@telfort.no','289 Reeves Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (136,'Netcom On-Line Communications Services','734-194-4455','Frank.Long2@libero.no','6349 Maxwell Ave.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (137,'OnlineWorx gmbh','1-824-5661','V.Symbouras@gmail.ca','7 Printing House Yard');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (138,'Dista','481-0180','Freddy.Mitchell5@dolfijn.it','01 Devonshire Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (139,'Casba','1-255-531-5727','William.Morton@mobileme.us','9 Willingdon Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (140,'WR WebDesign','1-354-1701','Martin.Langham@aol.fr','46 Carolyn Close');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (141,'Niops Software','506-2477','IDavis1@live.org','337 Greenheath Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (142,'Djing Oil','1-890-508-7529','Richard.Overton@dolfijn.cc','296 Fox Creek Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (143,'Milford Bank','205-6994','T.Van Dinter2@yahoo.org','8 Ninth Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (144,'Nongo Informatix','819-328-0615','Ann.Climent4@mymail.dk','7 E. Broward Blvd.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (145,'PSINet','637-987-0034','BrentJones@libero.be','71 E. Broward Blvd.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (146,'Triple Solutions','1-314-347-5393','Hans.Wong1@mymail.cn','16 Tremont Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (147,'NorthGo Deuren','1-158-956-4182','MattJulieze@gawab.it','1767 Trenton Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (148,'StepStone','1-501-6664','OttoGua Lima@web.de','3361 Southwest Blvd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (149,'Ethical Generics','1-535-2314','E.Zurich@telefonica.us','220 27th Street North');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (150,'Cisco Systems','1-146-780-5013','TonThompson@dolfijn.ca','585 Arlington Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (151,'NovoNordisk','629-095-8159','P.Antonucci@gawab.ca','1933 Hunt Valley Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (152,'Sapanda.com','065-8994','FredAnderson3@mymail.dk','46 South MacArthur');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (153,'Heraut Solutions','495-1194','Brend.Gonzalez@yahoo.net','852 North Irvington');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (154,'BetterOffice','1-163-557-1838','MattijsSchubert@libero.de','475 Madden Blvd.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (155,'ShopCentrale BV','814-838-0648','BillHarness@lycos.org','526 Braemar Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (156,'HZ Consult','1-916-967-0653','SuusStannard2@kpn.ca','15 Hill Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (157,'CIBA','213-608-0791','KCaffray@mobileme.de','4224 Woodside Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (158,'Nokia','1-380-9177','Frans.Stevens1@msn.fr','4 Barrenger Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (159,'Carey and Burns Services','325-163-9944','G.Watson@kpn.org','580 N. Sherman Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (160,'Michelin','065-9720','Patrick.Nefos@mail.es','868 Linden Ridge Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (161,'Meinders Meubelen','1-903-7102','WillMoon2@msn.es','74 Chehalis Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (162,'Brioco','1-745-946-3961','FemkeLezniak3@telefonica.de','4 N. Hope Av');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (163,'UV Tech','576-796-9098','I.Herzog3@dolfijn.fr','58 Braemar Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (164,'Check Point Software Technologies','335-1649','Royvan Dijk@gmail.us','091 Broomhouse Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (165,'Van Winden Beveiliging','400-500-9805','FredOyler@msn.org','2557 Jefferson Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (166,'Intuit','092-6421','LBrown1@libero.ca','3978 Corporate Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (167,'DotNet','1-156-0679','Trees.Sirabella@live.it','22 South MacArthur');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (168,'Akwalampa Uniel','1-761-5088','MattijsMillis@gawab.org','557 E. Marions Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (169,'KRX Consult','1-407-5415','Femke.Byrnes5@weboffice.co.uk','725 Fontanoso Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (170,'PTT Telecom','833-562-9725','Hans.Raines@excite.it','41 River Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (171,'PTT Telecom','1-895-711-4042','TonDavis@telfort.ca','5 Canyon Crest Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (172,'Burns and Dalton Data Solutions','446-9681','Roy.Nelson@mobileme.dk','4755 Woodside Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (173,'Ebonso Systems','1-295-3606','RichardSterrett1@mobileme.dk','72 Clearwater Pkwy');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (174,'Raptor Systems','198-7921','P.Poplock2@dolfijn.ca','990 Roan Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (175,'JanssenCilag','1-817-697-0980','Frans.Sterrett@libero.cn','9082 Swallowtail Ct.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (176,'Walker Tools bv','1-643-8603','GPhillips@freeweb.gov','32 Centerville Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (177,'ShopCentrale BV','496-4231','S.Donatelli4@aol.org','614 Wicksicam Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (178,'Mortrop','077-2513','K.Dulisse@mymail.be','99 Durness Place');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (179,'Marks and Stewart Finance','1-781-5207','Trees.Rivers@yahoo.fr','6 Fox Squirrel Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (180,'Schering','461-3086','Bianca.Millikin4@dolfijn.net','006 Buckthorn Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (181,'Philips','1-266-658-9801','Rick.Miller@libero.co.uk','8 N. Deerwood Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (182,'KMTraining','962-1579','JohanGildersleeve@dolfijn.be','80 Penny Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (183,'Zjongy International','329-1123','MickHulshof@mobileme.it','98 Freeman St');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (184,'Boehringer Ingelheim','997-145-4843','BiancaStevenson@excite.es','914 Highland Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (185,'Devote Informatics','1-028-8516','G.Schlee5@myspace.cc','2997 Brooke Valley Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (186,'MRP Data','022-619-5030','L.van Dijk4@freeweb.no','0427 Summer Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (187,'MiraVori','1-575-6277','Bas.Knopp@web.co.uk','436 Spottswood Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (188,'Lycos','1-586-359-6718','Fred.Sterrett@mail.cn','0583 Melrose Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (189,'FTP Software','1-539-331-5289','TreesStevens5@dolfijn.com','014 Walsh Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (190,'Unisol Paneel BV','546-4583','E.White5@myspace.cc','907 Glenridge Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (191,'Roghuis Consultancy','1-518-9642','Mattijs.Nithman@yahoo.nl','29 Village Road South');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (192,'HV Montage','1-762-665-0685','PetraCantere@aol.de','8603 Wellington Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (193,'Brierman Consultancy','1-762-3779','D.Brown@kpn.dk','0253 Close Gardens Court');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (194,'BLogic','1-274-2315','David.Jenssen4@msn.cc','33 Warwick Square');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (195,'Weber Koeltechniek BV','1-215-289-6000','G.Ionescu@weboffice.co.uk','465 Broomhouse Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (196,'Djong Oil','573-8605','George.van Goes5@live.nl','551 Canyon Crest Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (197,'Trendhopper','857-1521','William.Jones@excite.org','59 Paddington Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (198,'Smith Kline&French','1-926-321-6089','BasRatliff@mobileme.no','62 Brimming Boulevard');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (199,'Sparta Cycle','159-816-9192','Rogier.Climent@aol.es','1 Morningside Dr');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (200,'Hoechst','623-901-2542','MikeMariojnisk3@lycos.ca','477 Wicksicam Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (201,'Secure Computing','1-953-8783','Dave.Petterson@freeweb.fr','14 Fontanoso Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (202,'FIAT','1-140-271-9380','William.Nadalin@mail.be','4 Rockville Pike');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (203,'BCC','1-075-3962','E.Thompson5@yahoo.gov','9634 Printing House Yard');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (204,'NAFR Solutions','1-580-3137','UChwatal@weboffice.com','981 Wicksicam Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (205,'Ethical Generics','1-598-793-9785','CHerring@dolfijn.de','5 Gilbert Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (206,'Adobe Systems','1-303-5563','Frank.Hardoon@gawab.dk','880 Dairy Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (207,'SAAB','984-3453','IDavis2@myspace.cc','28 Faught Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (208,'POET','936-5790','BrentHamilton5@lycos.de','289 Arlington Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (209,'VV Architecture','640-2541','PetraMalone3@kpn.be','5 Arlington Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (210,'Taca','1-193-7625','AliceKorkovski4@lycos.it','8 Canyon Crest Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (211,'Notalya Consultancy','1-289-6986','I.Pyland4@gmail.fr','1 South 62th Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (212,'Michelin','170-163-8580','Frans.Young@hotmail.org','1019 Summer Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (213,'Macromedia','786-346-4850','WilliamDean@telfort.it','2375 Mount Helena Av.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (214,'AK Group','1-598-7096','VSimonent2@kpn.es','15 Woodcote Valley Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (215,'Sharpe and Grant IT Services','292-0266','Ton.Love3@dolfijn.fr','0812 Close Gardens Court');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (216,'Petronas','1-208-7558','Femke.Hummel@aol.fr','21 Nez Perce Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (217,'Aegon','646-751-2505','HansGildersleeve@dolfijn.net','4753 Glenridge Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (218,'PT WebDesign','1-964-141-1382','J.Mitchell@myspace.nl','39 East 74th Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (219,'GoodWorks gmbh','418-0390','P.Antonucci1@gawab.es','250 Elmar Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (220,'EADS','896-0738','GLawton@kpn.nl','382 Fairfield Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (221,'Hessersmitt','1-559-217-2810','Pablo.Ditmanen1@lycos.fr','789 Ninth Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (222,'MerckSharp&Dohme','1-473-832-1294','Bianca.Ostanik1@libero.be','85 Penny Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (223,'Premenos Technology','935-512-7899','Mattijs.Braconi@hotmail.cn','7 Stony Field Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (224,'Satinex','1-600-6123','Milan.Toreau@telefonica.fr','73 Serena Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (225,'Peugeot','850-941-5176','Kylie.Swaine5@telfort.co.uk','2 Everglades Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (226,'Schneider','791-3871','BasPrior@msn.gov','4 Centerville Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (227,'Astra','922-351-1084','Victoria.Symbouras4@live.com','059 Paddington Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (228,'JanssenCilag','184-1375','Martin.Schubert@freeweb.com','40 W. Broadway');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (229,'Djongo','1-690-145-0433','HMcCrary3@telfort.dk','1198 Linden Ridge Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (230,'3Com','460-3523','Suus.Davis3@live.be','7568 West 13th Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (231,'ParkeDavis','1-679-238-3318','WillPrior3@web.ca','2 Dallas Parkway');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (232,'YQ Tech','441-9065','Petra.Turk3@telefonica.ca','8 Brimming Boulevard');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (233,'Netmanage Inc.','1-560-894-2089','HMoore5@mymail.co.uk','491 Grassmere Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (234,'Abbot','1-419-4036','Mattijs.Browne@freeweb.nl','4 Spottswood Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (235,'Tesco','1-336-9848','SuusMoore@lycos.cc','6 Victoria Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (236,'NARG Solutions','1-441-289-6126','Nigel.Polti1@freeweb.org','23 Business Center Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (237,'Alinca Systems','1-957-572-5735','Mike.LeGrand@gmail.org','31 Devonshire Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (238,'Mingy Services','311-1962','VincentPhelps4@msn.org','8124 E. Plumb Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (239,'Open Market','091-3203','WilliamNewman@mymail.com','2 Harrison rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (240,'Meinders Meubelen','1-782-0815','Will.Young@hotmail.net','91 27th Street North');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (241,'Cascade Communications','1-182-128-5386','Lindsy.Matthew5@freeweb.be','464 Danielle Ct.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (242,'GreenConsult','1-346-8433','Frank.Long@dolfijn.be','397 Grassmere Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (243,'Telefonica','117-2048','Fred.Oyler2@lycos.be','1 Edith Marie Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (244,'Cascade Communications','1-494-313-1923','G.Nobles@telfort.gov','0720 W. Rand Rd.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (245,'Cage and Ritter Technology','1-615-5622','William.Herrin@weboffice.ca','48 Chalmette Court');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (246,'TRMM Transport','586-5965','JohnHoogbandt@web.be','52 Sarasota St.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (247,'FlyCheapAir','908-038-2702','JackReames@yahoo.es','27 Woodcote Valley Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (248,'Meinders Meubelen','1-982-9570','FransStevenson@yahoo.es','3713 Mount Helena Av.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (249,'Schneider','932-1264','Fred.Hoyt@telefonica.fr','29 Reeves Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (250,'HGNG Consultancy','1-080-157-1374','Mattijs.Bernstein@msn.gov','421 Arlington Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (251,'Kreitlar Management','411-3413','JWilliamson5@freeweb.com','4479 University ave.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (252,'Boehringer Ingelheim','1-574-569-0753','William.Moore@freeweb.fr','456 Woodside Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (253,'Pepsi','1-248-757-0116','KWilson@gawab.ca','9475 Southwest Blvd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (254,'MerckSharp&Dohme','661-580-9131','BasJessen2@telfort.cn','2345 Vanderheck');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (255,'PhoenixAero','374-692-5043','Peter.Chapman@msn.ca','7 Grant Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (256,'Lilly','1-595-919-4427','M.Moore@telfort.co.uk','4 Wicksicam Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (257,'FIAT','671-151-9644','Frank.Buchholz4@telefonica.no','9823 Chesterfield Road South');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (258,'Compuserve','1-512-8495','B.Ecchevarri5@gawab.be','14 South Wacker Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (259,'SoftQuad International','1-821-616-9349','Patty.Makelaar@live.nl','448 Alder Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (260,'Mister Vision','1-396-874-9613','VictoriaFernandez1@msn.be','51 Amadonna Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (261,'Zotono','128-914-7157','FransSymms5@telfort.cn','1029 Carolyn Close');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (262,'Mortrop','998-495-8998','SRobertson3@msn.es','2 N. Glenoaks Blvd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (263,'RQ Technics','1-668-586-8590','FredRoyal@libero.no','2 River Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (264,'Van Winden Verzekering','902-2158','IsoldeStannard1@excite.de','598 Redwood Ave.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (265,'RB Bank','1-012-1409','William.Hamilton5@telefonica.nl','9096 Walkers Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (266,'YW Technics','902-9776','H.Dittrich1@freeweb.dk','13 Shallowford Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (267,'MiraVori','530-854-0630','HansShapiro@kpn.us','332 Simpson Place');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (268,'Spyglass','1-926-063-4398','MattijsBrowne2@live.com','9382 South MacArthur');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (269,'TimesMedia','568-5900','Rick.Allison1@myspace.cn','0716 Virginia Foothills Dr');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (270,'Van Wiegen Constructies','1-683-884-8755','V.DeBerg@weboffice.cc','397 Nortman Blvd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (271,'Intuit','873-8873','GBrown@mobileme.com','95 N. Pine Grove');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (272,'Desktop Data','115-8980','Brent.Wolpert3@kpn.dk','03 Shallowford Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (273,'FTP Software','157-808-8847','DRichter5@mymail.co.uk','2818 Chinook Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (274,'CWIX Finance','696-0317','G.Morton@freeweb.us','4 Danielle Ct.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (275,'InnoTechnology','949-8775','HankOtto@lycos.cn','6 Wellington Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (276,'Rabobank','1-491-3067','CMcgrew@gawab.gov','46 Carroll Center Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (277,'FTP Software','1-092-371-1196','G.Watson3@web.ca','0 Redwood Ave.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (278,'Edu Solutions','1-678-352-9591','Peter.Millikin@gawab.dk','67 Weber Street North');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (279,'Spectradat','1-592-4284','B.Baltec@gawab.es','8 Roan Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (280,'Weber Koeltechniek BV','1-670-819-9641','GPickering@dolfijn.org','362 Forest Windway');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (281,'Van Toorn Adviseurs','614-838-8407','T.Noteboom5@excite.cn','113 Eastman Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (282,'Waltman Works','1-798-712-6414','CSwaine@yahoo.be','2 Greenheath Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (283,'Euroderma','071-3075','LiamIjukop5@mail.co.uk','9 Tuckahoe St');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (284,'Van Toorn Montage','644-594-4759','EStevenson@kpn.ca','39 Victoria Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (285,'TimesVision','769-301-8778','Richard.Jones@weboffice.com','3 Willowcrest');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (286,'Compuserve','551-7694','RNahay@hotmail.be','22 Gaston Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (287,'GreenSoftware','668-540-4677','LucyMaribarski5@web.dk','6 Amadonna Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (288,'Ethical Generics','278-399-3787','GWilliamson@mobileme.dk','1 Springfield Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (289,'Van Wiegen Montage','1-066-5470','Kay.Polti2@kpn.ca','0 Palos Verdes Mall');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (290,'NBBS Bank','172-154-2518','SuzanneBertelson5@live.it','25 Reeves Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (291,'Kovotna Consultants','760-7085','PetraPraeger2@live.com','540 Everglades Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (292,'U.S. Order','1-548-6063','IPoissant@msn.co.uk','1 Sulgrave Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (293,'VocalTec','616-3463','SJackson1@msn.net','064 West 9th Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (294,'Hannover Bank','504-834-0826','JohnBlacher3@lycos.cc','1932 Foxway');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (295,'JKL Bank','1-674-465-8914','Brent.Cramer@libero.it','7 North Fuller Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (296,'Schering','621-015-9991','Leo.Thaler1@aol.net','8632 Wilder St.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (297,'GreenShopToGo','891-766-8641','Maarten.Reames3@web.gov','3619 Danielle Ct.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (298,'Zotomo','381-6603','VictorGoodman@lycos.de','1 Spottswood Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (299,'Richardson and Rogers Consultancy','468-6512','GWatson@excite.de','6 Sarasota St.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (300,'GreatWorx gmbh','407-591-3686','GeorgeFrancis4@gawab.nl','47 Village Road South');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (301,'PTWebDesign','458-400-3319','L.Krutkov5@mobileme.nl','830 Hunt Valley Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (302,'MCNG Software','912-362-3186','R.Zia@mobileme.co.uk','176 Harrison rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (303,'Brasserie De Meiden','1-332-480-0724','NickDepew4@hotmail.es','496 Business Center Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (304,'KHTR Transport','485-493-7181','EStockton@kpn.de','8 Hidden Valley Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (305,'FinlandAir','980-4520','Trees.Gieske@libero.be','234 Unbridle Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (306,'Interbew','406-0721','Trees.Chwatal2@gawab.de','15 Chinook Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (307,'OneSoftware','310-048-4472','GeoffryKuehn2@live.cn','04 2th Ave.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (308,'Secure Computing','1-029-617-0109','Pauline.Phillips1@kpn.net','82 R. Wright Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (309,'OnlineWorx','664-402-4023','Bianca.Nahay@telefonica.be','309 S. Brackbank Dr');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (310,'Chekfree','569-202-8019','K.Grote3@mymail.co.uk','807 Station Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (311,'Warner Lambert','1-951-9186','FrankBoyer@msn.fr','8 Gilbert Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (312,'Scandia','359-1850','RDuvall@lycos.net','7264 NW 111th Loop');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (313,'CanadaAero','953-513-0259','YCaffray@msn.ca','0 Canyon Crest Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (314,'IMAX','1-887-1460','NickEmerson@telfort.org','83 Canyon Crest Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (315,'Ylinca Tech','690-299-9280','Richard.Voigt@myspace.no','90 Sarasota St.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (316,'Van Vliesman Adviseurs','1-251-734-3255','Will.Pyland@yahoo.no','24 Regency Plaza');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (317,'Van Walen Beveiliging','514-769-4145','Dan.Uprovski5@telfort.no','3 Brooke Valley Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (318,'Eelanco Tech','1-732-831-8925','PeterHarder@freeweb.org','443 Chehalis Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (319,'DenmarkAero','1-177-375-8521','HLong2@libero.ca','4923 Tuckahoe St');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (320,'Free Record Shop','1-814-751-7272','R.Kingslan1@weboffice.es','814 Elm Place');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (321,'HV Montage','1-120-329-2469','G.Goodman@web.dk','19 Village Road East');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (322,'BVNG Consultancy','367-2987','Geoffry.Guethlein2@live.no','680 Reeves Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (323,'Trapshop','069-606-4113','Y.Sakurai@telfort.gov','2 Regency Plaza');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (324,'NovoNordisk','1-933-8839','ERaines@mymail.cc','87 Fairfield Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (325,'Karwei Bouwmarkt','052-4192','JamesMoore@telefonica.us','684 Carnaby Creek');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (326,'Weekamp Deuren','179-8727','Sydney.Friedman@libero.net','35 Unbridle Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (327,'Roussel','854-234-9109','VincentPaul@web.cc','7 Highland Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (328,'Vardisio','259-5091','FransWargula@telfort.cc','480 N Broadway');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (329,'Inbox Solutions','1-991-8027','VVisentini@gmail.it','8715 Chinook Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (330,'Beecham','1-787-119-8684','ECappello@telfort.net','9998 Sungrave Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (331,'VOF De Vlinder','1-990-8976','Maarten.Van Dinter@gawab.be','012 Fontanoso Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (332,'Milan Bank','1-409-4362','Michael.Davis@mymail.fr','9724 Sulgrave Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (333,'Van Boschker Woonwinkel','167-4410','Peter.Mcnally@web.no','817 Hunt Valley Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (334,'Cisco Systems','1-285-8747','Bas.Geoppo@myspace.com','8 Walkers Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (335,'Macromedia','1-123-3078','AliceMariojnisk@weboffice.it','9 University ave.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (336,'HV Montage','1-924-850-2818','Dick.Cross2@live.fr','5406 North Irvington');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (337,'Chekfree','415-5183','BillVostreys4@yahoo.be','8 Arlington Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (338,'Firefox Communications','1-861-9653','James.Schmidt@web.be','794 Business Center Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (339,'KPTR Communications','715-492-0584','HHulshof2@mymail.co.uk','92 Windbrook Crs');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (340,'Rabobank','1-171-5450','RGriffioen3@telfort.be','1067 Centerville Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (341,'OrangeShopToGo','692-8973','GeorgeArden@yahoo.us','01 Gilbert Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (342,'HV Montage','1-616-642-1692','Matt.Baltec@yahoo.org','3181 Spottswood Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (343,'Kreitlar Management','606-534-0185','Nick.Knopp@mail.nl','337 N. Deerwood Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (344,'Van Dijk Boeken','354-3631','Bill.Bergdahl2@web.co.uk','3271 Colette street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (345,'Imtech','1-819-480-5721','Johan.Slater2@myspace.dk','1 East 74th Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (346,'Ikea','1-276-997-7334','NadineLangham@myspace.be','6131 Sungrave Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (347,'Wang Computers','925-541-2871','PattyLawton@mymail.us','3604 South Main');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (348,'Heraut Solutions BV','1-168-986-8513','JohanDaughtery1@telfort.nl','3 Scrutton Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (349,'Free Record Shop','1-635-837-9717','YFreed5@weboffice.fr','38 Perimeter Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (350,'NAKL Solutions','1-317-332-4456','BiancaFreed3@freeweb.org','2 Swan Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (351,'Open Market','1-405-6225','Ann.Brown@mail.nl','9016 Charlotte Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (352,'GreenPoint','1-547-0626','YWakefield4@telfort.gov','170 Willingdon Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (353,'Datanamic Solutions BV','908-422-7109','Frank.Ray@aol.com','418 W. Broadway');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (354,'Johnson & Johnson','1-418-941-3054','RToreau@kpn.fr','69 Jefferson Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (355,'DotNet','1-971-644-0716','SydneyStannard4@live.es','60 Warwick Square');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (356,'Johnson & Johnson','1-634-156-5994','V.Visentini3@mobileme.fr','144 Paddington Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (357,'V&D','1-620-7179','Franky.Mcgrew@freeweb.es','81 Woodside Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (358,'YV Works','505-674-4994','KimSimonent4@gmail.cc','7291 Mercury Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (359,'Unisol Paneel BV','874-1957','RPaul@mobileme.com','9 King Salmon Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (360,'Eelonco Systems','1-572-9605','PStevens@gmail.es','9637 Chesterfield Road South');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (361,'EB Tech','519-288-4433','BrentComeau@myspace.com','0 Sutter St');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (362,'Bencard','1-768-6157','I.Stockton3@mail.it','4589 Paddington Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (363,'JanssenCilag','731-635-1624','PabloHuffsmitt1@hotmail.com','7 Palos Verdes Mall');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (364,'Nucom','1-593-387-0208','Dan.Pensec@gawab.com','5846 Tuckahoe St');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (365,'BigWorx co','1-448-704-0566','Gretsj.Julieze@yahoo.us','1469 Walsh Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (366,'Scheider','091-047-9761','Maarten.Wicks@mymail.com','93 West MacArthur');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (367,'BMW','299-9608','P.DelRosso4@msn.de','27 Edith Marie Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (368,'Djong Informatics','954-987-9688','YBoyer1@telefonica.be','6067 Chesterfield Road South');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (369,'Cisco Systems','914-564-7965','Leo.Hummel4@hotmail.cc','9 N. Hope Av');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (370,'Van Tonen Verzekering','1-254-702-5049','H.Reyes@hotmail.fr','138 N. Hope Av');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (371,'Lucan','1-381-3394','Frank.DeWald1@hotmail.it','1860 Shallowford Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (372,'Winner Media','1-745-931-3366','LPraeger@hotmail.es','3965 Meadow Walk');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (373,'MetLife','660-390-1650','Freddy.Miller@mobileme.co.uk','6643 Walsh Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (374,'Abbot','1-611-454-5122','OliverDitmanen1@msn.de','481 One Park Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (375,'MerckSharp&Dohme','1-328-324-4023','Gretsj.Pekaban@kpn.cn','3 Broomhouse Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (376,'Van Boschker Constructies','174-7707','NickChwatal@dolfijn.gov','1033 Chinook Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (377,'Poolta','737-5040','GeoffryCantere5@mobileme.co.uk','2023 Fox Squirrel Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (378,'Van Vliet Accountancy','1-416-593-2048','Leon.Julieze@freeweb.com','59 NW 111th Loop');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (379,'Interbew','773-7049','EBarnett@gawab.cn','3512 High Palms Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (380,'JanssenCilag','537-006-9303','GOstanik@telefonica.co.uk','5384 Weber Street North');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (381,'Glenwood','1-004-676-9728','FrankSlater@mymail.gov','017 South Main');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (382,'Super Confex','1-305-875-8007','YDeans@freeweb.de','841 Chinook Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (383,'UStep','1-936-478-4731','Frank.Lamere@telfort.no','860 High Palms Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (384,'BeterBed','731-499-2082','G.Moreau@telfort.it','824 Victoria Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (385,'PlanSystems bv','109-278-0679','J.Deleo4@aol.be','346 Sulgrave Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (386,'Weber Koeltechniek','314-971-1142','Alice.Ditmanen@yahoo.be','30 Spottswood Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (387,'GoodSoftware','1-822-943-0689','MilanCarlos@live.cn','956 North MacArthur');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (388,'Broadband Technologies','1-450-0909','JohanDaughtery3@libero.com','0 King George Hwy');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (389,'Excite','688-772-0116','Hans.Lee@web.co.uk','8634 N Broadway');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (390,'Njing Oil','181-199-2534','Bianca.Clark3@weboffice.cc','3 2th Ave.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (391,'HV Montage','149-5851','Nick.Allison@mail.net','591 Meadow Walk');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (392,'Alena Tech','926-002-9047','HToreau@msn.gov','5 Forest Windway');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (393,'KMConsult','100-251-3900','V.Whitehurst3@telfort.cn','184 Village Road East');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (394,'Ebonso Communications','1-942-4820','T.Sharp3@weboffice.org','430 Jefferson Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (395,'Weber Koeltechniek BV','1-249-6182','D.DeBerg2@mobileme.nl','544 W. Rand Rd.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (396,'Unilever','819-323-9177','Brent.Paddock2@mymail.nl','139 Clearwater Pkwy');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (397,'United States Postal Service','744-1683','Ton.Yinger3@gawab.be','692 Eisenhower Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (398,'Kreitlar Management','1-820-554-1175','JohanWesolowski@yahoo.be','4965 J. Carcione Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (399,'Van Waal Beveiliging','222-760-7932','BillNobles@kpn.no','321 NW 111th Loop');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (400,'Schering','1-845-908-3018','H.Markovi1@freeweb.de','045 Windbrook Crs');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (401,'Weber Koeltechniek','1-079-0486','HansMcDaniel4@mail.net','1523 Waterford Blvd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (402,'Richards and Spencer IT Solutions','486-5823','G.Naff@kpn.be','0466 Madden Blvd.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (403,'NUNG Software','602-5375','H.Ahlgren@telfort.fr','77 Edith Marie Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (404,'Hill Worx bv','524-838-8178','RichardHelfrich1@kpn.fr','99 Muzzatta Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (405,'Vardisio','513-5206','WilliamMcDaniel@myspace.cn','25 Gascony Pl.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (406,'Compuserve','1-516-6554','RMatthew5@mail.es','1 Gascony Pl.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (407,'RT Communications','191-2040','Matt.Van Toorenbeek@gmail.com','7118 Brimming Boulevard');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (408,'KQR Communications','1-926-2515','Jean.Robbins5@excite.be','82 Fox Creek Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (409,'Dacia','650-4270','E.Thompson5@weboffice.cc','35 E. Marions Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (410,'UB Finance','302-795-1143','Trees.McCormick@gmail.org','17 Amadonna Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (411,'EADS','1-853-097-7811','FreddyRatliff1@kpn.cn','852 South 85th Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (412,'Blata','1-560-0887','Bill.Archer3@telfort.es','080 Waterford Blvd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (413,'Atalanka','837-040-1555','H.Yinger@gmail.org','25 Muzzatta Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (414,'Grupo Santander','727-267-3853','HMairy@excite.com','044 King Salmon Place');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (415,'Niops Software','1-146-5326','J.Sirabella@web.gov','3197 Harrison rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (416,'Nokia','318-8844','Trees.Knopp@hotmail.no','66 Braemar Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (417,'VocalTec','1-693-9493','MaddyCrocetti4@mobileme.net','7 Village Road South');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (418,'Sparta Cycle','436-477-4069','VWooten5@aol.com','123 Warren Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (419,'Akwalampa Uniel','1-640-6964','SydneyRobertson1@telfort.be','4646 Faught Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (420,'Eloncor Communications','1-213-8805','INahay@mail.co.uk','752 Chehalis Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (421,'Macromedia','1-697-7613','RogerReyes1@web.fr','8982 Charlotte Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (422,'Poolta','1-396-587-9752','Victoria.Storrs@telefonica.de','1866 North MacArthur');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (423,'Netscape Communications','1-630-7784','Agnes.Igolavski@lycos.us','33 Nez Perce Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (424,'Nuco','1-257-372-3488','Johan.Love2@mobileme.us','2 Fox Squirrel Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (425,'DotNet','1-970-627-2396','Camilla.Bugno@telfort.gov','69 Torin Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (426,'Njingy Services','851-3152','Fred.Liddle2@libero.de','6856 Woodcote Valley Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (427,'Sync Tech','1-885-1081','Ann.Brennan@excite.co.uk','498 East 74th Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (428,'Compuserve','1-695-9106','L.Jenssen3@lycos.es','325 Stewart Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (429,'Orion','475-138-8106','RickCaouette@live.gov','287 Meadow Walk');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (430,'IDEX','1-317-115-9879','Bart.Hummel@kpn.es','7 Grassmere Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (431,'Van Sterkendam Beveiliging','1-759-361-4417','J.Brumley@mobileme.ca','46 Warm Spring Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (432,'YV Works','1-758-7651','PierreWood1@yahoo.fr','7 N. Central Ave.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (433,'Evans','1-358-1202','PeterSeibel1@mymail.it','891 Freidrich Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (434,'RB Tech','1-037-8603','D.Trainor@kpn.es','69 Stewart Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (435,'Aerial Survey','1-824-0012','MichaelMoore@excite.ca','99 Gilbert Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (436,'MySQL AB','755-519-3415','James.Barnett@mail.fr','5 Gascony Pl.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (437,'Weekamp Deuren','1-949-6768','GVostreys1@dolfijn.gov','4 Edith Marie Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (438,'HVS Systems','1-486-707-0965','MaartenHoogbandt1@msn.es','5 S. Maryland Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (439,'Volkswagen AB','687-348-3742','BillMiller@weboffice.net','4 High Palms Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (440,'PTT Telecom','472-093-2437','LynnMillis5@msn.gov','498 Edith Marie Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (441,'Akwalampa Uniel','1-425-963-5860','NickWilson@kpn.co.uk','32 Morningside Dr');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (442,'Bank Labouchere','664-843-7736','WilliamHendrix4@yahoo.fr','8 Eastman Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (443,'Dacia','1-664-5282','GHaynes3@excite.net','909 Lindstrom Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (444,'SpainAero','1-816-631-2511','Peter.Ray5@msn.dk','7 Oak Leaf Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (445,'KKKW Consult','1-780-340-4014','V.Zimmerman1@dolfijn.dk','786 Stokes Rd.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (446,'Chekfree','1-997-221-5468','Bob.Uprovski2@myspace.us','8 Chalmette Court');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (447,'Martinair','020-9874','Milan.Patricelli3@gawab.gov','5 Freidrich Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (448,'Sapanda.com','920-746-5792','RichardSpensley1@telfort.com','94 Spottswood Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (449,'Brierman Consultancy','162-1238','YHendrix@lycos.us','37 Carolyn Close');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (450,'JetAir','595-634-5248','Rick.Clark4@excite.gov','1223 Victoria Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (451,'SilverData','489-4937','Fred.Jones@telefonica.be','1674 Shallowford Rd');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (452,'ItalyAero','405-5081','RickForsberg@yahoo.com','7 Foxway');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (453,'ETP Food','797-638-4018','BiancaWatson@mymail.it','05 Scrutton Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (454,'Raptor Systems','1-239-7897','PKeller@telefonica.co.uk','527 Braemar Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (455,'Philips','1-362-9592','PMejia2@libero.be','286 Bryant Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (456,'Gamma Holding','262-2329','KimMenovosa1@kpn.nl','93 Southfern Ct');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (457,'Ritter and Pitt Finance','861-187-1277','M.Uprovski3@kpn.de','934 W. Sunnyside Ave.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (458,'LW Builders','1-126-0933','KKnight5@gmail.it','7 Vanderheck');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (459,'UXG Tech','710-1306','GeorgeDuvall2@kpn.co.uk','1 Buckthorn Lane');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (460,'Aegon','1-304-1960','AgnesGriffioen1@mail.org','38 Bryant Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (461,'Ahold','1-195-5603','L.Cohen3@gmail.com','2 Muzzatta Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (462,'Russell and Ritter IT Services','389-222-5703','NickWolpert@web.fr','4 Elm Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (463,'ERNG Consultancy','879-9791','KWeaver@dolfijn.com','0654 South 86th Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (464,'Van Vliet Woonwinkel','1-511-3697','Fred.Sakurai3@gawab.no','8 Woodside Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (465,'RDB Bank','1-371-7809','C.Chwatal@libero.cn','92 Shawnee Ct');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (466,'Van Teken Verzekering','062-4161','JZurich@weboffice.es','7365 Hill Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (467,'SunRiver','864-403-7713','JHardoon@aol.nl','9296 Brandon Marshall Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (468,'SoftQuad International','1-165-192-2824','T.Symbouras4@freeweb.nl','40 Fontanoso Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (469,'OrangeData','072-6101','Freddy.Huston1@aol.ca','9521 Barrenger Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (470,'Van Tonen Bouw','363-9161','William.Vostreys4@weboffice.cc','1 Medford St');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (471,'Unique Technology','359-1461','PImhoff4@mobileme.dk','0 Meadow Walk');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (472,'Fluid Management','1-759-6722','EPoplock@gawab.cn','65 Warm Spring Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (473,'Mecklermedia Corp.','434-965-4939','RSeibel@libero.org','4 Wellington Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (474,'Cybercash','930-6682','L.Wood@lycos.be','864 Morningside Dr');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (475,'7-Eleven','1-348-567-8374','FreddyLawton@mobileme.de','9 New London Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (476,'Martinair','547-334-1380','PierreDavis4@libero.de','0764 Ferro Dr');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (477,'Numos','887-023-4951','S.Barnett4@dolfijn.net','7 Highland Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (478,'Infoseek','1-107-4788','Rick.Press@myspace.net','064 Colette street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (479,'Re Training','1-802-9758','RogierStorrs@mail.fr','8414 Village Road South');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (480,'TRKL Finance','412-8172','KPearlman1@mymail.us','668 Business Center Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (481,'Wehkamp BV','1-736-4597','FredPaddock@mymail.us','7 Gaston Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (482,'Van Meten Uitzendbureau','786-530-8710','FredArcher@telfort.ca','4086 Floribunda Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (483,'HaTeHa','1-433-9279','RLawton4@telefonica.de','752 Carolyn Close');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (484,'ItalyAir','1-640-845-0302','NigelLeonarda@aol.nl','5512 Everglades Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (485,'Petronas','1-247-3974','LeoAhlgren5@weboffice.it','456 Alder Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (486,'PlanWorx ltd','1-908-3632','DPetterson@dolfijn.us','16 Jefferson Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (487,'Les Chanterel','812-6786','FredMayberry2@msn.no','0437 Eastman Drive');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (488,'Scheider','829-403-6691','C.Toreau3@kpn.es','012 Trenton Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (489,'Imtech','1-533-4255','Jean.Friedman3@lycos.cc','71 Eisenhower Avenue');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (490,'Pitt Systems ltd','449-539-6761','S.Bitmacs5@web.net','638 Everglades Way');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (491,'ERS Group','890-255-1260','Patty.van der Laar@freeweb.us','43 Brandon Marshall Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (492,'GoodWorks co','402-0131','NickNahay4@web.co.uk','2233 Scrutton Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (493,'Brierman Consultancy','263-4890','YAntonucci3@mymail.cc','08 Woodcote Valley Road');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (494,'Cisco Systems','797-409-2683','Rico.Schmidt1@lycos.co.uk','156 Nez Perce Street');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (495,'Washinghton Bank','017-4473','FransHendrix1@msn.cn','4688 W. Rand Rd.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (496,'Check Point Software Technologies','1-998-417-7150','DavidKorkovski@mymail.be','4143 Melrose Ave');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (497,'Scholtes Vleeswaren','543-8386','Otto.Igolavski1@mail.no','4 27th Street North');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (498,'Calder Worx corp','228-078-3181','BasKing5@myspace.fr','2350 Southfern Ct');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (499,'Lennon and Spencer IT Services','1-279-311-9674','Petra.Roger3@libero.cc','889 Linden Ridge Dr.');
INSERT INTO "public"."socio" ("idsocio","nombre","telefono","email","direccion") VALUES (500,'NexxTech','1-064-516-4822','TSanders@libero.gov','9026 Danielle Ct.');