INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (1,'Dreams Leave-In Protein','DISPONIBLE','A733972',014.25);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (2,'Rutabaga','DISPONIBLE','A078304',95232.44);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (3,'Winter Squash','DISPONIBLE','P626932',47681.25);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (4,'Spice Basket','DISPONIBLE','A540700',46.73);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (5,'Ground Cherries','DISPONIBLE','A792649',10.94);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (6,'Echinacea','DISPONIBLE','P064893',1.19);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (7,'Leeks','DISPONIBLE','P056600',826.90);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (8,'BAMBOO SKEWERS','DISPONIBLE','A114278',5.90);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (9,'Okra','DISPONIBLE','A836535',699.52);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (10,'Almond Oil','DISPONIBLE','A125751',9.79);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (11,'Perennial Onions','DISPONIBLE','A409798',33489.60);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (12,'Goto Kola','DISPONIBLE','A954547',45660.75);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (13,'Cauliflower','DISPONIBLE','P976504',385.45);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (14,'Premier Bath Pak','DISPONIBLE','P836339',4.23);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (15,'Cinnamon Spice','DISPONIBLE','A661687',3.23);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (16,'ARTICHOKE HEARTS','DISPONIBLE','P991313',5.9);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (17,'Kohlrabi','DISPONIBLE','A647044',6806.11);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (18,'Yucca Root','DISPONIBLE','A278352',79.12);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (19,'FONDANT','DISPONIBLE','P520063',10.64);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (20,'TEA NESTEA','DISPONIBLE','P274948',0999.08);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (21,'Canning Tomatoes','DISPONIBLE','A575476',08628.28);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (22,'GARLIC MIST AERO','DISPONIBLE','P757601',3.87);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (23,'TABLE BLACK XLARGE','DISPONIBLE','P026520',6.68);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (24,'Lavender Oil','DISPONIBLE','P615472',71964.47);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (25,'Perennial Onions','DISPONIBLE','A573668',39.38);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (26,'CANNOLI SHELLS','DISPONIBLE','P380586',61598.10);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (27,'METAL SIDE CHAIR BLACK','DISPONIBLE','A975393',5010.78);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (28,'Super Herb Diet Formula','DISPONIBLE','P716944',551.68);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (29,'ORANGES MANDARIN','DISPONIBLE','A897689',38.79);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (30,'Liquid Gold Styling Glaze','DISPONIBLE','A631073',9836.42);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (31,'Pycnogenol','DISPONIBLE','P929603',4.47);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (32,'Cat''s Claw','DISPONIBLE','A345240',336.49);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (33,'Clove Oil','DISPONIBLE','A570393',018.71);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (34,'Okra','DISPONIBLE','A929945',24334.43);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (35,'PUDDING VANILLA DEAN','DISPONIBLE','A646395',273.37);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (36,'COASTERS PPR','DISPONIBLE','A145934',24139.70);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (37,'GATORADE LEMON LIME','DISPONIBLE','P517497',32.07);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (38,'GREEN SALAD BOWL','DISPONIBLE','A476954',86947.46);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (39,'Sweet Bell Peppers','DISPONIBLE','A599534',84.76);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (40,'Bilberry','DISPONIBLE','P650167',92.84);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (41,'FEATHER DUSTER OSTRICH','DISPONIBLE','A700112',981.01);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (42,'ORANGES MANDARIN','DISPONIBLE','A001406',4.67);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (43,'Kava Kava','DISPONIBLE','A311099',8363.28);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (44,'Echinacea','DISPONIBLE','P147287',1495.35);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (45,'PEPPERS RED DRY STRING','DISPONIBLE','A508807',6.46);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (46,'Parsley','DISPONIBLE','P773146',2.74);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (47,'Pycnogenol','DISPONIBLE','P583346',0.72);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (48,'HAMBURG DILL CHIPS','DISPONIBLE','A033869',5124.87);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (49,'SARDINES IN MUSTARD','DISPONIBLE','A570526',51.84);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (50,'Sausalito Spice Tea','DISPONIBLE','A581018',8482.62);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (51,'Coenzyme (CoQ-10)','DISPONIBLE','P473416',73522.94);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (52,'Red Tomatoes','DISPONIBLE','P379768',0189.08);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (53,'Snow Peas','DISPONIBLE','P225032',3306.16);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (54,'MEZZI RIGATONI','DISPONIBLE','A197765',76473.83);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (55,'Bilberry','DISPONIBLE','P868322',28356.48);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (56,'JERKY BEEF PEPPERED','DISPONIBLE','P850749',74.77);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (57,'BANQUET RL WHITE','DISPONIBLE','P596789',794.21);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (58,'CHIP DISH SHELL','DISPONIBLE','P281112',9406.88);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (59,'GARLIC MIST AERO','DISPONIBLE','P031266',28.09);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (60,'TEA NESTEA','DISPONIBLE','P069047',2493.12);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (61,'ELBOW MACARONI','DISPONIBLE','P334851',927.27);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (62,'Yellow Tomatoes','DISPONIBLE','A451901',2.42);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (63,'Evening Primrose Oil','DISPONIBLE','A853162',59.40);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (64,'Gourds','DISPONIBLE','A119312',1085.23);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (65,'Metabo Right','DISPONIBLE','P681963',69202.08);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (66,'Watermelon','DISPONIBLE','P231468',8134.20);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (67,'Ornamental Wheat','DISPONIBLE','P403370',8745.34);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (68,'SALSA RED PEPPER','DISPONIBLE','P703890',33.86);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (69,'PEAR HALVES','DISPONIBLE','P415988',3675.16);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (70,'Shark Cartilage','DISPONIBLE','A042843',05653.31);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (71,'WATER DASANI BTL','DISPONIBLE','A612454',13.83);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (72,'Swiss Chard','DISPONIBLE','A297893',62.30);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (73,'Feverfew','DISPONIBLE','P491879',2901.04);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (74,'Muscle Magic with Emu Oil','DISPONIBLE','P931067',9573.92);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (75,'ORANGES MANDARIN','DISPONIBLE','P318526',758.85);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (76,'CHERRIES  BRANDY/BOOT','DISPONIBLE','P119943',94616.98);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (77,'BEEF JERKY ORIGINAL','DISPONIBLE','A806207',52977.52);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (78,'FONDANT','DISPONIBLE','A520589',363.44);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (79,'GATORADE FRUIT PUNCH','DISPONIBLE','P206883',69.94);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (80,'PEACHES SLICED','DISPONIBLE','P947761',2016.83);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (81,'Red Raspberry','DISPONIBLE','P456886',4.98);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (82,'St. John''s Wort','DISPONIBLE','A038063',15761.02);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (83,'Ginkgo Biloba','DISPONIBLE','P259725',48.08);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (84,'COASTERS PPR','DISPONIBLE','P741741',5.19);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (85,'Tomatoes','DISPONIBLE','A611518',94160.98);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (86,'Rutabaga','DISPONIBLE','A700601',63258.11);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (87,'GATORADE GLACIER ICE','DISPONIBLE','P252426',2.94);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (88,'OIL OLIVE X VIR APULIAN','DISPONIBLE','A196201',7.87);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (89,'Coenzyme Q-10','DISPONIBLE','A530341',3947.44);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (90,'My Helping Heart','DISPONIBLE','A804294',69584.18);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (91,'Tomatoes','DISPONIBLE','A556825',17.91);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (92,'Books','DISPONIBLE','P902498',3093.19);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (93,'DHEA','DISPONIBLE','A584771',72143.00);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (94,'Metabo Right','DISPONIBLE','P657326',58.88);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (95,'Kale','DISPONIBLE','A135938',18.34);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (96,'ELBOWS WHOLE WHEAT','DISPONIBLE','P186489',2.81);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (97,'BAGS PRECUT','DISPONIBLE','P471030',6.04);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (98,'GARLIC MIST AERO','DISPONIBLE','P631031',8463.68);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (99,'JERKY BEEF TERIKAKI','DISPONIBLE','P266569',6.10);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (100,'Peppermint Oil','DISPONIBLE','A718085',6.49);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (101,'SKEWERS WOODEN','DISPONIBLE','A325680',2597.62);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (102,'Devils Claw','DISPONIBLE','P439516',85.48);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (103,'RAISIN COOKIE FILLED','DISPONIBLE','P537298',0.79);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (104,'Package Deals','DISPONIBLE','P571398',3.87);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (105,'BEVERAGE CUP','DISPONIBLE','A018480',4.51);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (106,'Evening Primrose Oil','DISPONIBLE','A395903',84929.18);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (107,'Peppers','DISPONIBLE','P519055',8.15);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (108,'Pycnogenol','DISPONIBLE','P119986',97.38);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (109,'TOPPING KRUNCH KOTE','DISPONIBLE','P408647',672.68);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (110,'Citrin','DISPONIBLE','A637958',28870.06);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (111,'Supplies','DISPONIBLE','P239798',1.52);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (112,'BEVERAGE CUP','DISPONIBLE','P170921',69.65);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (113,'TABLECOVER CLOSEOUT','DISPONIBLE','A515007',33482.93);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (114,'Cucumbers','DISPONIBLE','P713527',6.39);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (115,'Devils Claw','DISPONIBLE','P244726',6194.86);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (116,'SALSA RED PEPPER','DISPONIBLE','A366013',05.42);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (117,'Yellow Tomatoes','DISPONIBLE','P530294',570.65);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (118,'Cauliflower','DISPONIBLE','P511520',4.42);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (119,'Lima Beans','DISPONIBLE','A175508',312.82);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (120,'Dreams Away Headache Cream','MANTENIMIENTO','A181859',94683.28);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (121,'Healthy Heart','MANTENIMIENTO','A066595',3903.24);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (122,'Tomatoes','MANTENIMIENTO','P609060',8.92);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (123,'PEAR HALVES','MANTENIMIENTO','A990608',01371.97);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (124,'GRIDDLE POLISH PAD','MANTENIMIENTO','P496234',7795.16);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (125,'Summer Squash','MANTENIMIENTO','P246226',9.86);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (126,'COOKING WINE RED BURGUNDY','MANTENIMIENTO','A949226',4116.80);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (127,'Swiss Chard','MANTENIMIENTO','A062969',014.76);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (128,'Snap Peas','MANTENIMIENTO','A845875',892.68);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (129,'Purple Tomatoes','MANTENIMIENTO','A838789',046.19);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (130,'Lavender Oil','MANTENIMIENTO','A958250',705.89);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (131,'Cinnamon Spice','MANTENIMIENTO','P344520',7.24);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (132,'SKEWERS WOODEN','MANTENIMIENTO','P685303',10530.32);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (133,'Supplies','MANTENIMIENTO','P381561',02785.04);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (134,'Mustard','MANTENIMIENTO','P353551',17556.45);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (135,'Lima Beans','MANTENIMIENTO','P039371',746.27);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (136,'JERKY BEEF PEPPERED','MANTENIMIENTO','P720601',56.69);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (137,'Squash','MANTENIMIENTO','A387388',8.00);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (138,'Shark Cartilage','MANTENIMIENTO','P207836',2.48);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (139,'Lavender Oil','MANTENIMIENTO','A291816',4604.07);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (140,'SPAGHETTI WHOLE WHEAT','MANTENIMIENTO','A341590',41179.48);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (141,'OLIVES STFD W/ANCHOVIE','MANTENIMIENTO','A166462',050.09);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (142,'Watermelon','MANTENIMIENTO','A126083',16491.39);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (143,'Dreams Away Headache Cream','MANTENIMIENTO','A932874',29165.89);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (144,'Herbal Detox Program','MANTENIMIENTO','P954616',60.73);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (145,'Dandelion','MANTENIMIENTO','P025400',9082.24);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (146,'TABLE BROWN SMALL','MANTENIMIENTO','P394431',18079.65);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (147,'TOPPING KRUNCH KOTE','MANTENIMIENTO','P775786',774.90);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (148,'CHERRIES  BRANDY/BOOT','MANTENIMIENTO','A807409',2223.57);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (149,'Premier Bath Pak','MANTENIMIENTO','P541705',22962.56);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (150,'CUP WHITE SMALL','MANTENIMIENTO','A209495',2.18);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (151,'ELBOWS WHOLE WHEAT','MANTENIMIENTO','A970215',4.40);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (152,'Spice Basket','MANTENIMIENTO','A871373',30358.99);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (153,'Barley Grass','MANTENIMIENTO','P002970',73203.62);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (154,'BAG POLY FOR POTATOES','MANTENIMIENTO','A192694',78.97);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (155,'Posters','MANTENIMIENTO','P245179',01.52);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (156,'PEAR HALVES','MANTENIMIENTO','A893942',70.39);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (157,'TACO SEASONING MIX','MANTENIMIENTO','P549355',81.98);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (158,'TEA NESTEA','MANTENIMIENTO','A353146',5.28);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (159,'Eucalyptus Oil','MANTENIMIENTO','A754823',61.17);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (160,'Damiana','MANTENIMIENTO','A410930',92283.21);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (161,'TEA NESTEA','MANTENIMIENTO','A927235',98819.55);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (162,'Pycnogenol','MANTENIMIENTO','P846312',31550.00);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (163,'PERRIER WATER','MANTENIMIENTO','A641579',09.52);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (164,'SHARK LOIN MAKO','MANTENIMIENTO','P981498',874.92);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (165,'Currant Tomatoes','MANTENIMIENTO','P617516',283.46);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (166,'CUT OUT FOOD DECO','MANTENIMIENTO','P055826',00686.89);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (167,'Posters','MANTENIMIENTO','A863783',9.11);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (168,'DESSERT SLEEVES RED','MANTENIMIENTO','A275566',138.87);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (169,'MEZZI RIGATONI','MANTENIMIENTO','P744200',89.46);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (170,'Snap Pole Beans','MANTENIMIENTO','A173852',878.43);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (171,'Dandelion','MANTENIMIENTO','P087002',5750.45);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (172,'NAPKIN CALEIGHS','MANTENIMIENTO','P523199',8.93);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (173,'TOOTSIE POPS','MANTENIMIENTO','A134462',573.46);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (174,'APPLE GRANNY SMITH','MANTENIMIENTO','P670580',9147.55);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (175,'JUICE LEMON 4GR','MANTENIMIENTO','P113233',06.50);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (176,'PERRIER WATER','MANTENIMIENTO','A983531',94.08);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (177,'Yucca Root','MANTENIMIENTO','P233407',9.56);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (178,'My Helping Heart','MANTENIMIENTO','A782482',848.72);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (179,'Eucamint','MANTENIMIENTO','A227343',17.77);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (180,'OLIVES STFD W/ANCHOVIE','MANTENIMIENTO','A864763',15242.39);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (181,'OLIVE MIST COATING','MANTENIMIENTO','P146428',845.80);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (182,'Turnips','MANTENIMIENTO','P381837',3.21);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (183,'Winter Squash','MANTENIMIENTO','A976722',34.38);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (184,'Southern/Cow Peas','MANTENIMIENTO','P634046',80.45);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (185,'HAM HOCKS','DISPONIBLE','P245281',40199.14);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (186,'Yellow Tomatoes','DISPONIBLE','P152953',847.95);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (187,'GREEN LENTILS','DISPONIBLE','A749524',79.54);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (188,'CANNOLI SHELLS','DISPONIBLE','A551986',279.74);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (189,'PEPPERS RED DRY STRING','DISPONIBLE','P557033',765.45);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (190,'Liquid Luster Shampoo','DISPONIBLE','A187766',91518.30);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (191,'COASTERS PPR','DISPONIBLE','A594985',716.55);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (192,'Supplies','DISPONIBLE','P693393',52136.62);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (193,'Dreams Leave-In Protein','DISPONIBLE','A673300',83496.35);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (194,'ELBOWS WHOLE WHEAT','DISPONIBLE','A327061',49.56);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (195,'GOJO HAND CLEANER LEMON','DISPONIBLE','P840983',07.55);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (196,'PUDDING VANILLA DEAN','DISPONIBLE','A656353',31134.18);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (197,'Hair Glow','DISPONIBLE','P542720',189.60);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (198,'Clove Oil','DISPONIBLE','A493721',73.60);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (199,'Tea Tree Oil','DISPONIBLE','P149722',58.52);
INSERT INTO "public"."item" ("id_item","nombre","estado","descripcion","precio") VALUES (200,'Flower Bulbs','DISPONIBLE','A238406',3617.66);